-- first remove any foreign key constraints
alter table if exists users
drop column id;

--drop tables in reverse order to make sure we have clean data bases to work with
drop table if exists users cascade;

--create the project table that is the most independent table
create table users (
    id integer primary key generated by default as identity,
    name text not null,
    email text not null,
    is_mentor boolean default 'false' not null,
    password text not null,
    join_date timestamptz default now() not null,
    open_sessions integer default '0' not null

);
