

--drop tables to make sure the tables will be clean
drop table if exists user_profile;

--declare the ENUM values for profession
create type profession as ENUM ('UI UX', 'Frontend Development','Backend Development', 'Fullstack Development');

--declare the ENUM for time zone
create type timezone as ENUM ('EST', 'PST', 'UTC', 'CTS', 'MST');

--create the project table that is the most independent table
create table user_profile (
    id integer primary key generated by default as identity,
    profession profession not null,
    phone text,
    discord_id text,
    location text,
    time_zone timezone,
    current_job_title text,
    current_job_company text,
    current_job_description text,
    current_job_start_date TIMESTAMPTZ default now(),
    past_job1_title text,
    past_job1_company text,
    past_job1_description text,
    past_job1_start_date TIMESTAMPTZ,
    past_job1_end_date TIMESTAMPTZ,
    past_job2_title text,
    past_job2_company text,
    past_job2_description text,
    past_job2_start_date TIMESTAMPTZ,
    past_job2_end_date TIMESTAMPTZ
);
