
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('Backend Development', '451-755-8850', 'Fundamental', 'Södra Sandby', 'UI Lead', 'AMD', 'I love programming and in my job I get to work with AI and ML tech to build the robots of the future', 1);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('Fullstack Development', '692-417-6618', '24/7', 'Paombong', 'Head of Development', 'Nvidia', 'I design beautiful technology in order to make peoples lives better', 2);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('Backend Development', '382-170-3814', 'Managed', 'Pellegrini', 'Dev Ops Director', 'IBM', 'I run highly skilled teams of developers to break new ground using cutting edge technology', 3);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('UI UX', '172-591-7376', 'well-modulated', 'Basista', 'UI Lead', 'Airtable', 'I love programming and in my job I get to work with AI and ML tech to build the robots of the future', 4);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('UI UX', '998-707-0095', 'Enhanced', 'Timurjaya', 'Head of Development', 'AMD', 'I design beautiful technology in order to make peoples lives better', 5);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('Frontend Development', '328-596-6414', 'Advanced', 'Bardaï', 'CTO', 'IBM', 'I love programming and in my job I get to work with AI and ML tech to build the robots of the future', 6);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('Fullstack Development', '500-648-0785', 'actuating', 'Srostki', 'Head of UX', 'AirBnB', 'I run highly skilled teams of developers to break new ground using cutting edge technology', 7);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('UI UX', '410-637-4190', 'system-worthy', 'Tayang', 'CTO', 'NASA', 'I design beautiful technology in order to make peoples lives better', 8);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('UI UX', '880-428-5285', 'Organized', 'Nanlang', 'Head of UX', 'NASA', 'I love programming and in my job I get to work with AI and ML tech to build the robots of the future', 9);
insert into user_profile (profession, phone, discord_id, location, job_title, job_company, job_description, user_id) values ('Backend Development', '283-185-4410', 'Distributed', 'Lodja', 'Dev Ops Director', 'Ebay', 'I love programming and in my job I get to work with AI and ML tech to build the robots of the future', 10);


-- to seed run
-- psql -U ryan -d connectful -f ./seeds/seed.connectful_user_profile.sql